//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hattai.payments.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoycooleaCL")]
        public string adyenMerchantAccount {
            get {
                return ((string)(this["adyenMerchantAccount"]));
            }
            set {
                this["adyenMerchantAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws@Company.Goycoolea")]
        public string adyenDirectPaymentUser {
            get {
                return ((string)(this["adyenDirectPaymentUser"]));
            }
            set {
                this["adyenDirectPaymentUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goycoolea1234$")]
        public string adyenDirectPaymentPwd {
            get {
                return ((string)(this["adyenDirectPaymentPwd"]));
            }
            set {
                this["adyenDirectPaymentPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pal-test.adyen.com/pal/servlet/soap/Payment")]
        public string com_hattai_core_payments_AdyenSandbox_Payment {
            get {
                return ((string)(this["com_hattai_core_payments_AdyenSandbox_Payment"]));
            }
            set {
                this["com_hattai_core_payments_AdyenSandbox_Payment"] = value;
            }
        }
    }
}
